apiVersion: v1
kind: Service
metadata:
  name: loki-gateway-public
  namespace: logging
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80 # public
      targetPort: 8080 # ACTUAL gateway port
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
